# Generated by Django 3.2.8 on 2021-10-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ExitTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
