# Generated by Django 3.2.8 on 2021-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_auto_20211015_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Price_Type',
            field=models.CharField(max_length=20),
        ),
    ]
